"""initial_all_tables

Revision ID: 47a3142a6ebb
Revises: 
Create Date: 2018-09-22 14:05:13.494588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47a3142a6ebb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('zid', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('last_name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('person_type', sa.VARCHAR(length=255), nullable=True),
    sa.Column('phone_number', sa.Integer(), nullable=True),
    sa.Column('email', sa.VARCHAR(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('photo_url', sa.String(length=128), nullable=True),
    sa.Column('available', sa.Boolean(), nullable=True),
    sa.Column('location', sa.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('zid')
    )
    op.create_index(op.f('ix_user_first_name'), 'user', ['first_name'], unique=False)
    op.create_index(op.f('ix_user_last_name'), 'user', ['last_name'], unique=False)
    op.create_index(op.f('ix_user_person_type'), 'user', ['person_type'], unique=False)
    op.create_index(op.f('ix_user_phone_number'), 'user', ['phone_number'], unique=False)
    op.create_table('interests',
    sa.Column('zid', sa.Integer(), nullable=False),
    sa.Column('study_time', sa.BIGINT(), nullable=True),
    sa.Column('study_length', sa.Integer(), nullable=True),
    sa.Column('serious', sa.Boolean(), nullable=True),
    sa.Column('sports', sa.VARCHAR(length=255), nullable=True),
    sa.Column('gaming', sa.VARCHAR(length=255), nullable=True),
    sa.ForeignKeyConstraint(['zid'], ['user.zid'], ),
    sa.PrimaryKeyConstraint('zid')
    )
    op.create_index(op.f('ix_interests_study_time'), 'interests', ['study_time'], unique=False)
    op.create_table('matcher',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('zid_src', sa.Integer(), nullable=True),
    sa.Column('zid_dest', sa.Integer(), nullable=True),
    sa.Column('match_time', sa.BIGINT(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('swiped_right', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['zid_dest'], ['user.zid'], ),
    sa.ForeignKeyConstraint(['zid_src'], ['user.zid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student',
    sa.Column('zid', sa.Integer(), nullable=False),
    sa.Column('degree', sa.VARCHAR(length=255), nullable=True),
    sa.Column('enrolled_courses', sa.VARCHAR(length=255), nullable=True),
    sa.Column('societies', sa.VARCHAR(length=255), nullable=True),
    sa.ForeignKeyConstraint(['zid'], ['user.zid'], ),
    sa.PrimaryKeyConstraint('zid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student')
    op.drop_table('matcher')
    op.drop_index(op.f('ix_interests_study_time'), table_name='interests')
    op.drop_table('interests')
    op.drop_index(op.f('ix_user_phone_number'), table_name='user')
    op.drop_index(op.f('ix_user_person_type'), table_name='user')
    op.drop_index(op.f('ix_user_last_name'), table_name='user')
    op.drop_index(op.f('ix_user_first_name'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
